import { Team } from './AppContext';
import { extraTeams } from './AppContextTeamsExtra';
import { finalTeams } from './AppContextTeamsExtra2';

// First 8 test teams with 10-digit phone numbers
const baseTeams: Team[] = [
  { id: '1', teamNumber: 1, name: 'Smith/Johnson', player1FirstName: 'John', player1LastName: 'Smith', player2FirstName: 'Mike', player2LastName: 'Johnson', phoneNumber: '5551234567', city: 'New York', registeredTournaments: ['1', '2'], bostonPotTournaments: ['1'], paymentStatus: 'paid', player1PaymentStatus: 'paid', player2PaymentStatus: 'paid', player1TournamentPayments: { '1': true, '2': true }, player2TournamentPayments: { '1': true, '2': true }, tournamentPayments: { '1': true, '2': true }, totalOwed: 0 },
  { id: '2', teamNumber: 2, name: 'Davis/Wilson', player1FirstName: 'Sarah', player1LastName: 'Davis', player2FirstName: 'Tom', player2LastName: 'Wilson', phoneNumber: '5551234568', city: 'Los Angeles', registeredTournaments: ['1', '2'], bostonPotTournaments: ['2'], paymentStatus: 'paid', player1PaymentStatus: 'paid', player2PaymentStatus: 'paid', player1TournamentPayments: { '1': true, '2': true }, player2TournamentPayments: { '1': true, '2': true }, tournamentPayments: { '1': true, '2': true }, totalOwed: 0 },
  { id: '3', teamNumber: 3, name: 'Brown/Taylor', player1FirstName: 'David', player1LastName: 'Brown', player2FirstName: 'Lisa', player2LastName: 'Taylor', phoneNumber: '5551234569', city: 'Chicago', registeredTournaments: ['1'], bostonPotTournaments: [], paymentStatus: 'partial', player1PaymentStatus: 'paid', player2PaymentStatus: 'unpaid', player1TournamentPayments: { '1': true }, player2TournamentPayments: { '1': false }, tournamentPayments: { '1': false }, totalOwed: 25 },
  { id: '4', teamNumber: 4, name: 'Miller/Anderson', player1FirstName: 'Chris', player1LastName: 'Miller', player2FirstName: 'Amy', player2LastName: 'Anderson', phoneNumber: '5551234570', city: 'Houston', registeredTournaments: ['2'], bostonPotTournaments: ['2'], paymentStatus: 'unpaid', player1PaymentStatus: 'unpaid', player2PaymentStatus: 'unpaid', player1TournamentPayments: { '2': false }, player2TournamentPayments: { '2': false }, tournamentPayments: { '2': false }, totalOwed: 50 },
  { id: '5', teamNumber: 5, name: 'Garcia/Rodriguez', player1FirstName: 'Carlos', player1LastName: 'Garcia', player2FirstName: 'Ana', player2LastName: 'Rodriguez', phoneNumber: '5551234571', city: 'Atlanta', registeredTournaments: ['1', '2'], bostonPotTournaments: ['1', '2'], paymentStatus: 'paid', player1PaymentStatus: 'paid', player2PaymentStatus: 'paid', player1TournamentPayments: { '1': true, '2': true }, player2TournamentPayments: { '1': true, '2': true }, tournamentPayments: { '1': true, '2': true }, totalOwed: 0 },
  { id: '6', teamNumber: 6, name: 'Lee/White', player1FirstName: 'Kevin', player1LastName: 'Lee', player2FirstName: 'Emma', player2LastName: 'White', phoneNumber: '5551234572', city: 'Phoenix', registeredTournaments: ['1'], bostonPotTournaments: [], paymentStatus: 'paid', player1PaymentStatus: 'paid', player2PaymentStatus: 'paid', player1TournamentPayments: { '1': true }, player2TournamentPayments: { '1': true }, tournamentPayments: { '1': true }, totalOwed: 0 },
  { id: '7', teamNumber: 7, name: 'Clark/Lewis', player1FirstName: 'Ryan', player1LastName: 'Clark', player2FirstName: 'Jessica', player2LastName: 'Lewis', phoneNumber: '5551234573', city: 'Denver', registeredTournaments: ['2'], bostonPotTournaments: [], paymentStatus: 'partial', player1PaymentStatus: 'paid', player2PaymentStatus: 'unpaid', player1TournamentPayments: { '2': true }, player2TournamentPayments: { '2': false }, tournamentPayments: { '2': false }, totalOwed: 25 },
  { id: '8', teamNumber: 8, name: 'Hall/Young', player1FirstName: 'Mark', player1LastName: 'Hall', player2FirstName: 'Rachel', player2LastName: 'Young', phoneNumber: '5551234574', city: 'Seattle', registeredTournaments: ['1', '2'], bostonPotTournaments: ['1'], paymentStatus: 'paid', player1PaymentStatus: 'paid', player2PaymentStatus: 'paid', player1TournamentPayments: { '1': true, '2': true }, player2TournamentPayments: { '1': true, '2': true }, tournamentPayments: { '1': true, '2': true }, totalOwed: 0 }
];

// Combine all 20 teams
export const sampleTeams: Team[] = [...baseTeams, ...extraTeams, ...finalTeams];