import { Team } from './AppContext';

// Final 6 test teams (15-20) with 10-digit phone numbers - using cities from the current city list
export const finalTeams: Team[] = [
  { id: '15', teamNumber: 15, name: 'Phillips/Campbell', player1FirstName: 'Greg', player1LastName: 'Phillips', player2FirstName: 'Carol', player2LastName: 'Campbell', phoneNumber: '5551234581', city: 'Columbus', registeredTournaments: ['1'], bostonPotTournaments: [], paymentStatus: 'pending', player1PaymentStatus: 'paid', player2PaymentStatus: 'pending', player1TournamentPayments: { '1': true }, player2TournamentPayments: { '1': false }, tournamentPayments: { '1': false }, totalOwed: 25 },
  { id: '16', teamNumber: 16, name: 'Parker/Evans', player1FirstName: 'Matt', player1LastName: 'Parker', player2FirstName: 'Helen', player2LastName: 'Evans', phoneNumber: '5551234582', city: 'Cincinnati', registeredTournaments: ['2'], bostonPotTournaments: ['2'], paymentStatus: 'pending', player1PaymentStatus: 'pending', player2PaymentStatus: 'pending', player1TournamentPayments: { '2': false }, player2TournamentPayments: { '2': false }, tournamentPayments: { '2': false }, totalOwed: 50 },
  { id: '17', teamNumber: 17, name: 'Edwards/Collins', player1FirstName: 'Ben', player1LastName: 'Edwards', player2FirstName: 'Diane', player2LastName: 'Collins', phoneNumber: '5551234583', city: 'Chicago', registeredTournaments: ['1', '2'], bostonPotTournaments: ['1', '2'], paymentStatus: 'paid', player1PaymentStatus: 'paid', player2PaymentStatus: 'paid', player1TournamentPayments: { '1': true, '2': true }, player2TournamentPayments: { '1': true, '2': true }, tournamentPayments: { '1': true, '2': true }, totalOwed: 0 },
  { id: '18', teamNumber: 18, name: 'Stewart/Morris', player1FirstName: 'Joe', player1LastName: 'Stewart', player2FirstName: 'Janet', player2LastName: 'Morris', phoneNumber: '5551234584', city: 'Detroit', registeredTournaments: ['1'], bostonPotTournaments: [], paymentStatus: 'paid', player1PaymentStatus: 'paid', player2PaymentStatus: 'paid', player1TournamentPayments: { '1': true }, player2TournamentPayments: { '1': true }, tournamentPayments: { '1': true }, totalOwed: 0 },
  { id: '19', teamNumber: 19, name: 'Sanchez/Rogers', player1FirstName: 'Luis', player1LastName: 'Sanchez', player2FirstName: 'Karen', player2LastName: 'Rogers', phoneNumber: '5551234585', city: 'Atlanta', registeredTournaments: ['2'], bostonPotTournaments: [], paymentStatus: 'pending', player1PaymentStatus: 'paid', player2PaymentStatus: 'pending', player1TournamentPayments: { '2': true }, player2TournamentPayments: { '2': false }, tournamentPayments: { '2': false }, totalOwed: 25 },
  { id: '20', teamNumber: 20, name: 'Reed/Cook', player1FirstName: 'Tony', player1LastName: 'Reed', player2FirstName: 'Nancy', player2LastName: 'Cook', phoneNumber: '5551234586', city: 'DC/Maryland', registeredTournaments: ['1', '2'], bostonPotTournaments: ['1'], paymentStatus: 'paid', player1PaymentStatus: 'paid', player2PaymentStatus: 'paid', player1TournamentPayments: { '1': true, '2': true }, player2TournamentPayments: { '1': true, '2': true }, tournamentPayments: { '1': true, '2': true }, totalOwed: 0 }
];