import { Team } from './AppContext';

// Additional 12 test teams (9-20) with 10-digit phone numbers - using cities from the current city list
export const extraTeams: Team[] = [
  { id: '9', teamNumber: 9, name: 'King/Wright', player1FirstName: 'Steve', player1LastName: 'King', player2FirstName: 'Nicole', player2LastName: 'Wright', phoneNumber: '5551234575', city: 'Cincinnati', registeredTournaments: ['1'], bostonPotTournaments: ['1'], paymentStatus: 'paid', player1PaymentStatus: 'paid', player2PaymentStatus: 'paid', player1TournamentPayments: { '1': true }, player2TournamentPayments: { '1': true }, tournamentPayments: { '1': true }, totalOwed: 0 },
  { id: '10', teamNumber: 10, name: 'Green/Adams', player1FirstName: 'Paul', player1LastName: 'Green', player2FirstName: 'Kate', player2LastName: 'Adams', phoneNumber: '5551234576', city: 'Chicago', registeredTournaments: ['2'], bostonPotTournaments: [], paymentStatus: 'pending', player1PaymentStatus: 'pending', player2PaymentStatus: 'pending', player1TournamentPayments: { '2': false }, player2TournamentPayments: { '2': false }, tournamentPayments: { '2': false }, totalOwed: 50 },
  { id: '11', teamNumber: 11, name: 'Baker/Nelson', player1FirstName: 'Jim', player1LastName: 'Baker', player2FirstName: 'Linda', player2LastName: 'Nelson', phoneNumber: '5551234577', city: 'Detroit', registeredTournaments: ['1', '2'], bostonPotTournaments: ['2'], paymentStatus: 'pending', player1PaymentStatus: 'paid', player2PaymentStatus: 'pending', player1TournamentPayments: { '1': true, '2': true }, player2TournamentPayments: { '1': false, '2': false }, tournamentPayments: { '1': false, '2': false }, totalOwed: 50 },
  { id: '12', teamNumber: 12, name: 'Hill/Carter', player1FirstName: 'Rob', player1LastName: 'Hill', player2FirstName: 'Susan', player2LastName: 'Carter', phoneNumber: '5551234578', city: 'Atlanta', registeredTournaments: ['1'], bostonPotTournaments: [], paymentStatus: 'paid', player1PaymentStatus: 'paid', player2PaymentStatus: 'paid', player1TournamentPayments: { '1': true }, player2TournamentPayments: { '1': true }, tournamentPayments: { '1': true }, totalOwed: 0 },
  { id: '13', teamNumber: 13, name: 'Mitchell/Perez', player1FirstName: 'Dan', player1LastName: 'Mitchell', player2FirstName: 'Maria', player2LastName: 'Perez', phoneNumber: '5551234579', city: 'DC/Maryland', registeredTournaments: ['2'], bostonPotTournaments: ['2'], paymentStatus: 'paid', player1PaymentStatus: 'paid', player2PaymentStatus: 'paid', player1TournamentPayments: { '2': true }, player2TournamentPayments: { '2': true }, tournamentPayments: { '2': true }, totalOwed: 0 },
  { id: '14', teamNumber: 14, name: 'Roberts/Turner', player1FirstName: 'Alex', player1LastName: 'Roberts', player2FirstName: 'Beth', player2LastName: 'Turner', phoneNumber: '5551234580', city: 'Other', registeredTournaments: ['1', '2'], bostonPotTournaments: ['1'], paymentStatus: 'paid', player1PaymentStatus: 'paid', player2PaymentStatus: 'paid', player1TournamentPayments: { '1': true, '2': true }, player2TournamentPayments: { '1': true, '2': true }, tournamentPayments: { '1': true, '2': true }, totalOwed: 0 }
];